sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t xeleniumz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker -e CI=true xeleniumz/react-test npm test 

after_success:
  - docker build -t xeleniumz/multi-client ./client 
  - docker build -t xeleniumz/multi-nginx ./nignx
  - docker build -t xeleniumz/multi-server ./server
  - docker build -t xeleniumz/multi-worker ./worker
  # login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  # push images to docker hub
  - docker push xeleniumz/multi-client
  - docker push xeleniumz/multi-nginx
  - docker push xeleniumz/multi-server
  - docker push xeleniumz/multi-worker
